title: "Preppy Pod"
description: "Apocalypse planning for normal people."
url: "https://preppypod.com"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Links
links:
  - title: "Apple"
    url: "#"
  - title: "Spotify"
    url: "#"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
